apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: 2018-10-28T10:08:44Z
    generateName: http-echo-deployment-6547c55ff4-
    labels:
      app: http-echo
      pod-template-hash: 6547c55ff4
    name: http-echo-deployment-6547c55ff4-bxjw8
    namespace: http-echo
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: http-echo-deployment-6547c55ff4
      uid: 7428a7ac-da99-11e8-85c2-080027ec1ed5
    resourceVersion: "18118"
    selfLink: /api/v1/namespaces/http-echo/pods/http-echo-deployment-6547c55ff4-bxjw8
    uid: 742e1e9f-da99-11e8-85c2-080027ec1ed5
  spec:
    containers:
    - image: http-echo:v1
      imagePullPolicy: IfNotPresent
      name: http-echo
      ports:
      - containerPort: 8181
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-x6vjv
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: master
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-x6vjv
      secret:
        defaultMode: 420
        secretName: default-token-x6vjv
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-10-28T10:08:44Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-10-28T10:08:47Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-10-28T10:08:47Z
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: 2018-10-28T10:08:44Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://8441b2a6987d750022e8c675244ae5aa2f2f05deb06e02cd656284ac26902022
      image: http-echo:v1
      imageID: docker-pullable://subodhp/http-echo@sha256:9b56677ed0f14a2bad15bf6a5a33fa4d76bc174728891fddca52264cc77cc5e0
      lastState: {}
      name: http-echo
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-10-28T10:08:46Z
    hostIP: 192.168.1.8
    phase: Running
    podIP: 10.244.0.54
    qosClass: BestEffort
    startTime: 2018-10-28T10:08:44Z
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"http-echo","namespace":"http-echo"},"spec":{"externalIPs":["192.168.56.101"],"ports":[{"port":9191,"protocol":"TCP","targetPort":8181}],"selector":{"app":"http-echo"}}}
    creationTimestamp: 2018-10-28T10:15:46Z
    name: http-echo
    namespace: http-echo
    resourceVersion: "19750"
    selfLink: /api/v1/namespaces/http-echo/services/http-echo
    uid: 6f821627-da9a-11e8-85c2-080027ec1ed5
  spec:
    clusterIP: 10.110.221.142
    externalIPs:
    - 192.168.56.101
    ports:
    - port: 9191
      protocol: TCP
      targetPort: 8181
    selector:
      app: http-echo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"http-echo-deployment","namespace":"http-echo"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"http-echo"}},"template":{"metadata":{"labels":{"app":"http-echo"}},"spec":{"containers":[{"image":"http-echo:v1","name":"http-echo","ports":[{"containerPort":8181}]}]}}}}
    creationTimestamp: 2018-10-28T10:08:44Z
    generation: 1
    name: http-echo-deployment
    namespace: http-echo
    resourceVersion: "18120"
    selfLink: /apis/apps/v1/namespaces/http-echo/deployments/http-echo-deployment
    uid: 7420111e-da99-11e8-85c2-080027ec1ed5
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: http-echo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: http-echo
      spec:
        containers:
        - image: http-echo:v1
          imagePullPolicy: IfNotPresent
          name: http-echo
          ports:
          - containerPort: 8181
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-10-28T10:08:47Z
      lastUpdateTime: 2018-10-28T10:08:47Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2018-10-28T10:08:44Z
      lastUpdateTime: 2018-10-28T10:08:47Z
      message: ReplicaSet "http-echo-deployment-6547c55ff4" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2018-10-28T10:08:44Z
    generation: 1
    labels:
      app: http-echo
      pod-template-hash: 6547c55ff4
    name: http-echo-deployment-6547c55ff4
    namespace: http-echo
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: http-echo-deployment
      uid: 7420111e-da99-11e8-85c2-080027ec1ed5
    resourceVersion: "18119"
    selfLink: /apis/apps/v1/namespaces/http-echo/replicasets/http-echo-deployment-6547c55ff4
    uid: 7428a7ac-da99-11e8-85c2-080027ec1ed5
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: http-echo
        pod-template-hash: 6547c55ff4
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: http-echo
          pod-template-hash: 6547c55ff4
      spec:
        containers:
        - image: http-echo:v1
          imagePullPolicy: IfNotPresent
          name: http-echo
          ports:
          - containerPort: 8181
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
